name: IPhoneMirror
options:
  minimumXcodeGenVersion: 2.42.0
  deploymentTarget:
    macOS: "14.0"
targets:
  IPhoneMirror:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pae.whoop.iphonemirror
        PRODUCT_NAME: IPhoneMirror
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_STYLE: Automatic
        ENABLE_USER_SCRIPT_SANDBOXING: "YES"
