name: KiriTaraMaru
options:
  bundleIdPrefix: com.bda
  deploymentTarget:
    iOS: "16.0"
packages:
  GenieMax:
    path: ../
settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: YG7X8EC59V
targets:
  GenieMaxiOS:
    type: application
    platform: iOS
    sources:
      - GenieMaxApp
    dependencies:
      - package: GenieMax
        product: GenieMax
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bda.innohub
        PRODUCT_NAME: KiriTaraMaru
        PRODUCT_MODULE_NAME: GenieMaxiOS
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "7"
        INFOPLIST_FILE: GenieMaxApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: YG7X8EC59V
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: "NO"
        ENABLE_USER_SCRIPT_SANDBOXING: "YES"
      configs:
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_OPTIMIZATION_LEVEL: "-O"
